SELECT CITY, OFFICE, SALES FROM OFFICES;
SELECT NAMES, REP_OFFICE, SALES, QUOTA FROM SALESREPS;
SELECT NAMES, SALES, QUOTA, (SALES - QUOTA) FROM SALESREPS;
SELECT NAMES, SALES, QUOTA, (SALES - QUOTA) FROM SALESREPS WHERE SALES < QUOTA;
/*
LIST LARGE ORDER IN THE DATABASE AND FIND OUT WHICH CUSTOMER PLACED THE
ORDER, WHICH PRODUCT WAS ORDERED AND IN WHICH QUANTITY, SQL CAN ALSO SORT 
THE ORDERS BASED ON ORDER AMOUNT
*/
SELECT ORDER_NUM, CUST, PRODUCT, QTY, AMOUNT, FROM ORDERS
WHERE AMOUNT > 25000.00
ORDER BY AMOUNT;

/**SUMMARIZE DATA E.G ASK FOR AVERAGE OF TOTAL ORDERS*/
SELECT AVG(AMOUNT) FROM ORDERS;

/* AVERAGE OF PARTICULAR CUSTOMER*/
SELECT AVG(AMOUNT) FROM ORDERS WHERE CUST = 2103;

/*FINDING OUT THE TOTAL VALUES OF ORDERS PLACED CUSTOMERS, 
YOU CAN ASK SQL TO GROUP THE ORDERS TOGETHER BY CUSTOMER NUMBER AND
THEN TOTAL THE ORDER FOR EACH CUSTOMERS */
SELECT CUST, SUM(AMOUNT) FROM ORDERS GROUP BY CUST;
